# LuaJIT fork of OGSR Engine. Built with msvcbuild.bat (a copy of the engine's 3rd_party\Src\luajit2\msvcbuild.bat), not CMake:
# the VM is generated by buildvm/minilua, and the flags match what the engine used before the move to vcpkg.
# Installs the Lua headers straight into include\ (the engine includes <lua.hpp>) and LuaJIT.lib.

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO joye-ramone/luajit2
    REF 584d1c235809cf41b4d942b520c88f3d6cb9bdcf
    SHA512 21704e7fd96eeacefd8ee5211ac5979b9834e0f2d36a27b0727576809770aa8c6a7abc5e55858fe9438595e6d0bc3088b84fe3d8a014f477dc44c35de6322c17
    HEAD_REF xray
)

# msvcbuild.bat builds in place, so every configuration gets its own copy of the sources
function(ogsr_luajit_build config crt suffix)
    set(build_dir "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-${suffix}")
    file(REMOVE_RECURSE "${build_dir}")
    file(COPY "${SOURCE_PATH}/" DESTINATION "${build_dir}")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/msvcbuild.bat" DESTINATION "${build_dir}")

    set(ENV{LJ_CRT} "${crt}")
    vcpkg_execute_required_process(
        COMMAND cmd /c msvcbuild.bat ${config} static
        WORKING_DIRECTORY "${build_dir}"
        LOGNAME "build-${TARGET_TRIPLET}-${suffix}"
    )
    if(NOT EXISTS "${build_dir}/src/LuaJIT.lib")
        message(FATAL_ERROR "msvcbuild.bat did not produce LuaJIT.lib, see build-${TARGET_TRIPLET}-${suffix}-out.log")
    endif()

    set(LUAJIT_BUILD_DIR_${suffix} "${build_dir}/src" PARENT_SCOPE)
endfunction()

if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
    ogsr_luajit_build(Release /MT rel)
    file(INSTALL "${LUAJIT_BUILD_DIR_rel}/LuaJIT.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
endif()

if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
    ogsr_luajit_build(Debug /MTd dbg)
    file(INSTALL "${LUAJIT_BUILD_DIR_dbg}/LuaJIT.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()

# luajit.h is generated by the build (genversion.lua from luajit_rolling.h + .relver)
if(DEFINED LUAJIT_BUILD_DIR_rel)
    set(header_dir "${LUAJIT_BUILD_DIR_rel}")
else()
    set(header_dir "${LUAJIT_BUILD_DIR_dbg}")
endif()
file(INSTALL "${header_dir}/lua.h" "${header_dir}/lualib.h" "${header_dir}/lauxlib.h" "${header_dir}/luaconf.h" "${header_dir}/lua.hpp" "${header_dir}/luajit.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/ogsr-luajit-config.cmake" "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYRIGHT")
